package ttc2019

import sum.tt._

import org.rosi_project.model_management.core._
import ttc2019.metamodels.create.Validator
import ttc2019.metamodels.create.Launcher

object ExampleCombiCaseOO extends App {

  SynchronizationCompartment combine RsumCompartment
  
  val loader = new TTCLoader()  
  val validator = new Launcher()
  val bddFileName = "Generated.bddmodel"
  val ttFileName = "TT.ttmodel"
  val ttEcoreName = "TT.ecore"
  
  val saver = loader.loadEcore(ttEcoreName, ttFileName)

  val i0 = new TruthTable("TableI4O2Seed42", null)
  val i1 = new InputPort("I0", null)
  val i2 = new InputPort("I1", null)
  val i3 = new InputPort("I2", null)
  val i4 = new InputPort("I3", null)
  val i5 = new OutputPort("O0", null)
  val i6 = new OutputPort("O1", null)
  val i7 = new Row(null)
  val i8 = new Cell(false, null)
  val i9 = new Cell(false, null)
  val i10 = new Cell(false, null)
  val i11 = new Cell(false, null)
  val i12 = new Cell(true, null)
  val i13 = new Cell(false, null)
  val i14 = new Row(null)
  val i15 = new Cell(true, null)
  val i16 = new Cell(false, null)
  val i17 = new Cell(false, null)
  val i18 = new Cell(false, null)
  val i19 = new Cell(true, null)
  val i20 = new Cell(false, null)
  val i21 = new Row(null)
  val i22 = new Cell(false, null)
  val i23 = new Cell(true, null)
  val i24 = new Cell(false, null)
  val i25 = new Cell(false, null)
  val i26 = new Cell(false, null)
  val i27 = new Cell(true, null)
  val i28 = new Row(null)
  val i29 = new Cell(true, null)
  val i30 = new Cell(true, null)
  val i31 = new Cell(false, null)
  val i32 = new Cell(false, null)
  val i33 = new Cell(false, null)
  val i34 = new Cell(true, null)
  val i35 = new Row(null)
  val i36 = new Cell(false, null)
  val i37 = new Cell(false, null)
  val i38 = new Cell(true, null)
  val i39 = new Cell(false, null)
  val i40 = new Cell(true, null)
  val i41 = new Cell(false, null)
  val i42 = new Row(null)
  val i43 = new Cell(true, null)
  val i44 = new Cell(false, null)
  val i45 = new Cell(true, null)
  val i46 = new Cell(false, null)
  val i47 = new Cell(true, null)
  val i48 = new Cell(false, null)
  val i49 = new Row(null)
  val i50 = new Cell(false, null)
  val i51 = new Cell(true, null)
  val i52 = new Cell(true, null)
  val i53 = new Cell(false, null)
  val i54 = new Cell(false, null)
  val i55 = new Cell(false, null)
  val i56 = new Row(null)
  val i57 = new Cell(true, null)
  val i58 = new Cell(true, null)
  val i59 = new Cell(true, null)
  val i60 = new Cell(false, null)
  val i61 = new Cell(false, null)
  val i62 = new Cell(true, null)
  val i63 = new Row(null)
  val i64 = new Cell(false, null)
  val i65 = new Cell(false, null)
  val i66 = new Cell(false, null)
  val i67 = new Cell(true, null)
  val i68 = new Cell(false, null)
  val i69 = new Cell(true, null)
  val i70 = new Row(null)
  val i71 = new Cell(true, null)
  val i72 = new Cell(false, null)
  val i73 = new Cell(false, null)
  val i74 = new Cell(true, null)
  val i75 = new Cell(true, null)
  val i76 = new Cell(true, null)
  val i77 = new Row(null)
  val i78 = new Cell(false, null)
  val i79 = new Cell(true, null)
  val i80 = new Cell(false, null)
  val i81 = new Cell(true, null)
  val i82 = new Cell(true, null)
  val i83 = new Cell(false, null)
  val i84 = new Row(null)
  val i85 = new Cell(true, null)
  val i86 = new Cell(true, null)
  val i87 = new Cell(false, null)
  val i88 = new Cell(true, null)
  val i89 = new Cell(false, null)
  val i90 = new Cell(false, null)
  val i91 = new Row(null)
  val i92 = new Cell(false, null)
  val i93 = new Cell(false, null)
  val i94 = new Cell(true, null)
  val i95 = new Cell(true, null)
  val i96 = new Cell(true, null)
  val i97 = new Cell(true, null)
  val i98 = new Row(null)
  val i99 = new Cell(true, null)
  val i100 = new Cell(false, null)
  val i101 = new Cell(true, null)
  val i102 = new Cell(true, null)
  val i103 = new Cell(false, null)
  val i104 = new Cell(true, null)
  val i105 = new Row(null)
  val i106 = new Cell(false, null)
  val i107 = new Cell(true, null)
  val i108 = new Cell(true, null)
  val i109 = new Cell(true, null)
  val i110 = new Cell(false, null)
  val i111 = new Cell(false, null)
  val i112 = new Row(null)
  val i113 = new Cell(true, null)
  val i114 = new Cell(true, null)
  val i115 = new Cell(true, null)
  val i116 = new Cell(true, null)
  val i117 = new Cell(true, null)
  val i118 = new Cell(false, null)
  (new TruthTableRowsRow(i0, i7)).initialize()
  (new TruthTableRowsRow(i0, i14)).initialize()
  (new TruthTableRowsRow(i0, i21)).initialize()
  (new TruthTableRowsRow(i0, i28)).initialize()
  (new TruthTableRowsRow(i0, i35)).initialize()
  (new TruthTableRowsRow(i0, i42)).initialize()
  (new TruthTableRowsRow(i0, i49)).initialize()
  (new TruthTableRowsRow(i0, i56)).initialize()
  (new TruthTableRowsRow(i0, i63)).initialize()
  (new TruthTableRowsRow(i0, i70)).initialize()
  (new TruthTableRowsRow(i0, i77)).initialize()
  (new TruthTableRowsRow(i0, i84)).initialize()
  (new TruthTableRowsRow(i0, i91)).initialize()
  (new TruthTableRowsRow(i0, i98)).initialize()
  (new TruthTableRowsRow(i0, i105)).initialize()
  (new TruthTableRowsRow(i0, i112)).initialize()
  (new TruthTablePortsPort(i0, i1)).initialize()
  (new TruthTablePortsPort(i0, i2)).initialize()
  (new TruthTablePortsPort(i0, i3)).initialize()
  (new TruthTablePortsPort(i0, i4)).initialize()
  (new TruthTablePortsPort(i0, i5)).initialize()
  (new TruthTablePortsPort(i0, i6)).initialize()
  (new RowCellsCell(i7, i8)).initialize()
  (new RowCellsCell(i7, i9)).initialize()
  (new RowCellsCell(i7, i10)).initialize()
  (new RowCellsCell(i7, i11)).initialize()
  (new RowCellsCell(i7, i12)).initialize()
  (new RowCellsCell(i7, i13)).initialize()
  (new CellPortPort(i8, i1)).initialize()
  (new CellPortPort(i9, i2)).initialize()
  (new CellPortPort(i10, i3)).initialize()
  (new CellPortPort(i11, i4)).initialize()
  (new CellPortPort(i12, i5)).initialize()
  (new CellPortPort(i13, i6)).initialize()
  (new RowCellsCell(i14, i15)).initialize()
  (new RowCellsCell(i14, i16)).initialize()
  (new RowCellsCell(i14, i17)).initialize()
  (new RowCellsCell(i14, i18)).initialize()
  (new RowCellsCell(i14, i19)).initialize()
  (new RowCellsCell(i14, i20)).initialize()
  (new CellPortPort(i15, i1)).initialize()
  (new CellPortPort(i16, i2)).initialize()
  (new CellPortPort(i17, i3)).initialize()
  (new CellPortPort(i18, i4)).initialize()
  (new CellPortPort(i19, i5)).initialize()
  (new CellPortPort(i20, i6)).initialize()
  (new RowCellsCell(i21, i22)).initialize()
  (new RowCellsCell(i21, i23)).initialize()
  (new RowCellsCell(i21, i24)).initialize()
  (new RowCellsCell(i21, i25)).initialize()
  (new RowCellsCell(i21, i26)).initialize()
  (new RowCellsCell(i21, i27)).initialize()
  (new CellPortPort(i22, i1)).initialize()
  (new CellPortPort(i23, i2)).initialize()
  (new CellPortPort(i24, i3)).initialize()
  (new CellPortPort(i25, i4)).initialize()
  (new CellPortPort(i26, i5)).initialize()
  (new CellPortPort(i27, i6)).initialize()
  (new RowCellsCell(i28, i29)).initialize()
  (new RowCellsCell(i28, i30)).initialize()
  (new RowCellsCell(i28, i31)).initialize()
  (new RowCellsCell(i28, i32)).initialize()
  (new RowCellsCell(i28, i33)).initialize()
  (new RowCellsCell(i28, i34)).initialize()
  (new CellPortPort(i29, i1)).initialize()
  (new CellPortPort(i30, i2)).initialize()
  (new CellPortPort(i31, i3)).initialize()
  (new CellPortPort(i32, i4)).initialize()
  (new CellPortPort(i33, i5)).initialize()
  (new CellPortPort(i34, i6)).initialize()
  (new RowCellsCell(i35, i36)).initialize()
  (new RowCellsCell(i35, i37)).initialize()
  (new RowCellsCell(i35, i38)).initialize()
  (new RowCellsCell(i35, i39)).initialize()
  (new RowCellsCell(i35, i40)).initialize()
  (new RowCellsCell(i35, i41)).initialize()
  (new CellPortPort(i36, i1)).initialize()
  (new CellPortPort(i37, i2)).initialize()
  (new CellPortPort(i38, i3)).initialize()
  (new CellPortPort(i39, i4)).initialize()
  (new CellPortPort(i40, i5)).initialize()
  (new CellPortPort(i41, i6)).initialize()
  (new RowCellsCell(i42, i43)).initialize()
  (new RowCellsCell(i42, i44)).initialize()
  (new RowCellsCell(i42, i45)).initialize()
  (new RowCellsCell(i42, i46)).initialize()
  (new RowCellsCell(i42, i47)).initialize()
  (new RowCellsCell(i42, i48)).initialize()
  (new CellPortPort(i43, i1)).initialize()
  (new CellPortPort(i44, i2)).initialize()
  (new CellPortPort(i45, i3)).initialize()
  (new CellPortPort(i46, i4)).initialize()
  (new CellPortPort(i47, i5)).initialize()
  (new CellPortPort(i48, i6)).initialize()
  (new RowCellsCell(i49, i50)).initialize()
  (new RowCellsCell(i49, i51)).initialize()
  (new RowCellsCell(i49, i52)).initialize()
  (new RowCellsCell(i49, i53)).initialize()
  (new RowCellsCell(i49, i54)).initialize()
  (new RowCellsCell(i49, i55)).initialize()
  (new CellPortPort(i50, i1)).initialize()
  (new CellPortPort(i51, i2)).initialize()
  (new CellPortPort(i52, i3)).initialize()
  (new CellPortPort(i53, i4)).initialize()
  (new CellPortPort(i54, i5)).initialize()
  (new CellPortPort(i55, i6)).initialize()
  (new RowCellsCell(i56, i57)).initialize()
  (new RowCellsCell(i56, i58)).initialize()
  (new RowCellsCell(i56, i59)).initialize()
  (new RowCellsCell(i56, i60)).initialize()
  (new RowCellsCell(i56, i61)).initialize()
  (new RowCellsCell(i56, i62)).initialize()
  (new CellPortPort(i57, i1)).initialize()
  (new CellPortPort(i58, i2)).initialize()
  (new CellPortPort(i59, i3)).initialize()
  (new CellPortPort(i60, i4)).initialize()
  (new CellPortPort(i61, i5)).initialize()
  (new CellPortPort(i62, i6)).initialize()
  (new RowCellsCell(i63, i64)).initialize()
  (new RowCellsCell(i63, i65)).initialize()
  (new RowCellsCell(i63, i66)).initialize()
  (new RowCellsCell(i63, i67)).initialize()
  (new RowCellsCell(i63, i68)).initialize()
  (new RowCellsCell(i63, i69)).initialize()
  (new CellPortPort(i64, i1)).initialize()
  (new CellPortPort(i65, i2)).initialize()
  (new CellPortPort(i66, i3)).initialize()
  (new CellPortPort(i67, i4)).initialize()
  (new CellPortPort(i68, i5)).initialize()
  (new CellPortPort(i69, i6)).initialize()
  (new RowCellsCell(i70, i71)).initialize()
  (new RowCellsCell(i70, i72)).initialize()
  (new RowCellsCell(i70, i73)).initialize()
  (new RowCellsCell(i70, i74)).initialize()
  (new RowCellsCell(i70, i75)).initialize()
  (new RowCellsCell(i70, i76)).initialize()
  (new CellPortPort(i71, i1)).initialize()
  (new CellPortPort(i72, i2)).initialize()
  (new CellPortPort(i73, i3)).initialize()
  (new CellPortPort(i74, i4)).initialize()
  (new CellPortPort(i75, i5)).initialize()
  (new CellPortPort(i76, i6)).initialize()
  (new RowCellsCell(i77, i78)).initialize()
  (new RowCellsCell(i77, i79)).initialize()
  (new RowCellsCell(i77, i80)).initialize()
  (new RowCellsCell(i77, i81)).initialize()
  (new RowCellsCell(i77, i82)).initialize()
  (new RowCellsCell(i77, i83)).initialize()
  (new CellPortPort(i78, i1)).initialize()
  (new CellPortPort(i79, i2)).initialize()
  (new CellPortPort(i80, i3)).initialize()
  (new CellPortPort(i81, i4)).initialize()
  (new CellPortPort(i82, i5)).initialize()
  (new CellPortPort(i83, i6)).initialize()
  (new RowCellsCell(i84, i85)).initialize()
  (new RowCellsCell(i84, i86)).initialize()
  (new RowCellsCell(i84, i87)).initialize()
  (new RowCellsCell(i84, i88)).initialize()
  (new RowCellsCell(i84, i89)).initialize()
  (new RowCellsCell(i84, i90)).initialize()
  (new CellPortPort(i85, i1)).initialize()
  (new CellPortPort(i86, i2)).initialize()
  (new CellPortPort(i87, i3)).initialize()
  (new CellPortPort(i88, i4)).initialize()
  (new CellPortPort(i89, i5)).initialize()
  (new CellPortPort(i90, i6)).initialize()
  (new RowCellsCell(i91, i92)).initialize()
  (new RowCellsCell(i91, i93)).initialize()
  (new RowCellsCell(i91, i94)).initialize()
  (new RowCellsCell(i91, i95)).initialize()
  (new RowCellsCell(i91, i96)).initialize()
  (new RowCellsCell(i91, i97)).initialize()
  (new CellPortPort(i92, i1)).initialize()
  (new CellPortPort(i93, i2)).initialize()
  (new CellPortPort(i94, i3)).initialize()
  (new CellPortPort(i95, i4)).initialize()
  (new CellPortPort(i96, i5)).initialize()
  (new CellPortPort(i97, i6)).initialize()
  (new RowCellsCell(i98, i99)).initialize()
  (new RowCellsCell(i98, i100)).initialize()
  (new RowCellsCell(i98, i101)).initialize()
  (new RowCellsCell(i98, i102)).initialize()
  (new RowCellsCell(i98, i103)).initialize()
  (new RowCellsCell(i98, i104)).initialize()
  (new CellPortPort(i99, i1)).initialize()
  (new CellPortPort(i100, i2)).initialize()
  (new CellPortPort(i101, i3)).initialize()
  (new CellPortPort(i102, i4)).initialize()
  (new CellPortPort(i103, i5)).initialize()
  (new CellPortPort(i104, i6)).initialize()
  (new RowCellsCell(i105, i106)).initialize()
  (new RowCellsCell(i105, i107)).initialize()
  (new RowCellsCell(i105, i108)).initialize()
  (new RowCellsCell(i105, i109)).initialize()
  (new RowCellsCell(i105, i110)).initialize()
  (new RowCellsCell(i105, i111)).initialize()
  (new CellPortPort(i106, i1)).initialize()
  (new CellPortPort(i107, i2)).initialize()
  (new CellPortPort(i108, i3)).initialize()
  (new CellPortPort(i109, i4)).initialize()
  (new CellPortPort(i110, i5)).initialize()
  (new CellPortPort(i111, i6)).initialize()
  (new RowCellsCell(i112, i113)).initialize()
  (new RowCellsCell(i112, i114)).initialize()
  (new RowCellsCell(i112, i115)).initialize()
  (new RowCellsCell(i112, i116)).initialize()
  (new RowCellsCell(i112, i117)).initialize()
  (new RowCellsCell(i112, i118)).initialize()
  (new CellPortPort(i113, i1)).initialize()
  (new CellPortPort(i114, i2)).initialize()
  (new CellPortPort(i115, i3)).initialize()
  (new CellPortPort(i116, i4)).initialize()
  (new CellPortPort(i117, i5)).initialize()
  (new CellPortPort(i118, i6)).initialize()


  //ModelElementLists.printAll()

  SynchronizationCompartment.integrateNewModel(BdtSumIntegration)

  println("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
  //ModelElementLists.printFromPackage("BDD")
  //ModelElementLists.printAll()

  WriteSumBdtOutput.generateEverything(bddFileName)

  validator.launch(ttFileName, bddFileName)

}



    