package ttc2019

import sum.tt._

import org.rosi_project.model_management.core._
import ttc2019.metamodels.create.Validator
import ttc2019.metamodels.create.Launcher

object ExampleCombiCase extends App {

  SynchronizationCompartment combine RsumCompartment

  val i0 = new TruthTable("Test", null)
  val i1 = new InputPort("a", null)
  val i2 = new InputPort("b", null)
  val i3 = new InputPort("c", null)
  val i4 = new InputPort("d", null)
  val i5 = new OutputPort("s", null)
  val i6 = new Row(null)
  val i7 = new Cell(false, null)
  val i8 = new Cell(false, null)
  val i9 = new Cell(false, null)
  val i10 = new Row(null)
  val i11 = new Cell(false, null)
  val i12 = new Cell(true, null)
  val i13 = new Cell(false, null)
  val i14 = new Cell(false, null)
  val i15 = new Cell(true, null)
  val i16 = new Row(null)
  val i17 = new Cell(false, null)
  val i18 = new Cell(true, null)
  val i19 = new Cell(false, null)
  val i20 = new Cell(true, null)
  val i21 = new Cell(false, null)
  val i22 = new Row(null)
  val i23 = new Cell(false, null)
  val i24 = new Cell(true, null)
  val i25 = new Cell(true, null)
  val i26 = new Cell(false, null)
  val i27 = new Row(null)
  val i28 = new Cell(true, null)
  val i29 = new Cell(false, null)
  val i30 = new Cell(false, null)
  val i31 = new Cell(false, null)
  val i32 = new Cell(false, null)
  val i33 = new Row(null)
  val i34 = new Cell(true, null)
  val i35 = new Cell(false, null)
  val i36 = new Cell(true, null)
  val i37 = new Cell(false, null)
  val i38 = new Cell(true, null)
  val i39 = new Row(null)
  val i40 = new Cell(true, null)
  val i41 = new Cell(true, null)
  val i42 = new Cell(false, null)
  val i43 = new Row(null)
  val i44 = new Cell(true, null)
  val i45 = new Cell(true, null)
  val i46 = new Cell(false, null)
  val i47 = new Cell(false, null)
  val i48 = new Cell(true, null)
  val i49 = new Row(null)
  val i50 = new Cell(true, null)
  val i51 = new Cell(true, null)
  val i52 = new Cell(true, null)
  val i53 = new Cell(false, null)
  val i54 = new Cell(false, null)
  (new TruthTableRowsRow(i0, i6)).initialize()
  (new TruthTableRowsRow(i0, i10)).initialize()
  (new TruthTableRowsRow(i0, i16)).initialize()
  (new TruthTableRowsRow(i0, i22)).initialize()
  (new TruthTableRowsRow(i0, i27)).initialize()
  (new TruthTableRowsRow(i0, i33)).initialize()
  (new TruthTableRowsRow(i0, i39)).initialize()
  (new TruthTableRowsRow(i0, i43)).initialize()
  (new TruthTableRowsRow(i0, i49)).initialize()
  (new TruthTablePortsPort(i0, i1)).initialize()
  (new TruthTablePortsPort(i0, i2)).initialize()
  (new TruthTablePortsPort(i0, i3)).initialize()
  (new TruthTablePortsPort(i0, i4)).initialize()
  (new TruthTablePortsPort(i0, i5)).initialize()
  (new RowCellsCell(i6, i7)).initialize()
  (new RowCellsCell(i6, i8)).initialize()
  (new RowCellsCell(i6, i9)).initialize()
  (new CellPortPort(i7, i1)).initialize()
  (new CellPortPort(i8, i2)).initialize()
  (new CellPortPort(i9, i5)).initialize()
  (new RowCellsCell(i10, i11)).initialize()
  (new RowCellsCell(i10, i12)).initialize()
  (new RowCellsCell(i10, i13)).initialize()
  (new RowCellsCell(i10, i14)).initialize()
  (new RowCellsCell(i10, i15)).initialize()
  (new CellPortPort(i11, i1)).initialize()
  (new CellPortPort(i12, i2)).initialize()
  (new CellPortPort(i13, i3)).initialize()
  (new CellPortPort(i14, i4)).initialize()
  (new CellPortPort(i15, i5)).initialize()
  (new RowCellsCell(i16, i17)).initialize()
  (new RowCellsCell(i16, i18)).initialize()
  (new RowCellsCell(i16, i19)).initialize()
  (new RowCellsCell(i16, i20)).initialize()
  (new RowCellsCell(i16, i21)).initialize()
  (new CellPortPort(i17, i1)).initialize()
  (new CellPortPort(i18, i2)).initialize()
  (new CellPortPort(i19, i3)).initialize()
  (new CellPortPort(i20, i4)).initialize()
  (new CellPortPort(i21, i5)).initialize()
  (new RowCellsCell(i22, i23)).initialize()
  (new RowCellsCell(i22, i24)).initialize()
  (new RowCellsCell(i22, i25)).initialize()
  (new RowCellsCell(i22, i26)).initialize()
  (new CellPortPort(i23, i1)).initialize()
  (new CellPortPort(i24, i2)).initialize()
  (new CellPortPort(i25, i3)).initialize()
  (new CellPortPort(i26, i5)).initialize()
  (new RowCellsCell(i27, i28)).initialize()
  (new RowCellsCell(i27, i29)).initialize()
  (new RowCellsCell(i27, i30)).initialize()
  (new RowCellsCell(i27, i31)).initialize()
  (new RowCellsCell(i27, i32)).initialize()
  (new CellPortPort(i28, i1)).initialize()
  (new CellPortPort(i29, i2)).initialize()
  (new CellPortPort(i30, i3)).initialize()
  (new CellPortPort(i31, i4)).initialize()
  (new CellPortPort(i32, i5)).initialize()
  (new RowCellsCell(i33, i34)).initialize()
  (new RowCellsCell(i33, i35)).initialize()
  (new RowCellsCell(i33, i36)).initialize()
  (new RowCellsCell(i33, i37)).initialize()
  (new RowCellsCell(i33, i38)).initialize()
  (new CellPortPort(i34, i1)).initialize()
  (new CellPortPort(i35, i2)).initialize()
  (new CellPortPort(i36, i3)).initialize()
  (new CellPortPort(i37, i4)).initialize()
  (new CellPortPort(i38, i5)).initialize()
  (new RowCellsCell(i39, i40)).initialize()
  (new RowCellsCell(i39, i41)).initialize()
  (new RowCellsCell(i39, i42)).initialize()
  (new CellPortPort(i40, i1)).initialize()
  (new CellPortPort(i41, i4)).initialize()
  (new CellPortPort(i42, i5)).initialize()
  (new RowCellsCell(i43, i44)).initialize()
  (new RowCellsCell(i43, i45)).initialize()
  (new RowCellsCell(i43, i46)).initialize()
  (new RowCellsCell(i43, i47)).initialize()
  (new RowCellsCell(i43, i48)).initialize()
  (new CellPortPort(i44, i1)).initialize()
  (new CellPortPort(i45, i2)).initialize()
  (new CellPortPort(i46, i3)).initialize()
  (new CellPortPort(i47, i4)).initialize()
  (new CellPortPort(i48, i5)).initialize()
  (new RowCellsCell(i49, i50)).initialize()
  (new RowCellsCell(i49, i51)).initialize()
  (new RowCellsCell(i49, i52)).initialize()
  (new RowCellsCell(i49, i53)).initialize()
  (new RowCellsCell(i49, i54)).initialize()
  (new CellPortPort(i50, i1)).initialize()
  (new CellPortPort(i51, i2)).initialize()
  (new CellPortPort(i52, i3)).initialize()
  (new CellPortPort(i53, i4)).initialize()
  (new CellPortPort(i54, i5)).initialize()

  //ModelElementLists.printAll()

  SynchronizationCompartment.integrateNewModel(BdtSumIntegration)

  println("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
  ModelElementLists.printFromPackage("BDD")
  //ModelElementLists.printAll()
  
  val bddFileName = "Generated.bddmodel"
  val ttFileName = "TTTest.ttmodel"
  
  WriteSumBdtOutput.generateEverything(bddFileName)
  
  val validator = new Launcher()
  
  validator.launch(ttFileName, bddFileName)


}



    