//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2019.BinaryDecision.Metamodels.BinaryDecisionDiagrams.BDD
{
    
    
    /// <summary>
    /// The default implementation of the BDD class
    /// </summary>
    [XmlIdentifierAttribute("name")]
    [XmlNamespaceAttribute("https://www.transformation-tool-contest.eu/2019/bdd")]
    [XmlNamespacePrefixAttribute("bdd")]
    [ModelRepresentationClassAttribute("https://www.transformation-tool-contest.eu/2019/bdd#//BDD")]
    [DebuggerDisplayAttribute("BDD {Name}")]
    public partial class BDD : ModelElement, IBDD, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Name property
        /// </summary>
        private string _name;
        
        private static Lazy<ITypedElement> _nameAttribute = new Lazy<ITypedElement>(RetrieveNameAttribute);
        
        private static Lazy<ITypedElement> _portsReference = new Lazy<ITypedElement>(RetrievePortsReference);
        
        /// <summary>
        /// The backing field for the Ports property
        /// </summary>
        private BDDPortsCollection _ports;
        
        private static Lazy<ITypedElement> _treeReference = new Lazy<ITypedElement>(RetrieveTreeReference);
        
        /// <summary>
        /// The backing field for the Tree property
        /// </summary>
        private ITree _tree;
        
        private static IClass _classInstance;
        
        public BDD()
        {
            this._ports = new BDDPortsCollection(this);
            this._ports.CollectionChanging += this.PortsCollectionChanging;
            this._ports.CollectionChanged += this.PortsCollectionChanged;
        }
        
        /// <summary>
        /// The name property
        /// </summary>
        [DisplayNameAttribute("name")]
        [CategoryAttribute("BDD")]
        [XmlElementNameAttribute("name")]
        [IdAttribute()]
        [XmlAttributeAttribute(true)]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    string old = this._name;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnNameChanging(e);
                    this.OnPropertyChanging("Name", e, _nameAttribute);
                    this._name = value;
                    this.OnNameChanged(e);
                    this.OnPropertyChanged("Name", e, _nameAttribute);
                }
            }
        }
        
        /// <summary>
        /// The ports property
        /// </summary>
        [LowerBoundAttribute(1)]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("ports")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("owner")]
        [ConstantAttribute()]
        public IOrderedSetExpression<IPort> Ports
        {
            get
            {
                return this._ports;
            }
        }
        
        /// <summary>
        /// The tree property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("tree")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("ownerBDD")]
        public ITree Tree
        {
            get
            {
                return this._tree;
            }
            set
            {
                if ((this._tree != value))
                {
                    ITree old = this._tree;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnTreeChanging(e);
                    this.OnPropertyChanging("Tree", e, _treeReference);
                    this._tree = value;
                    if ((old != null))
                    {
                        old.OwnerBDD = null;
                        old.Parent = null;
                        old.ParentChanged -= this.OnResetTree;
                    }
                    if ((value != null))
                    {
                        value.OwnerBDD = this;
                        value.Parent = this;
                        value.ParentChanged += this.OnResetTree;
                    }
                    this.OnTreeChanged(e);
                    this.OnPropertyChanged("Tree", e, _treeReference);
                }
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new BDDChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new BDDReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("https://www.transformation-tool-contest.eu/2019/bdd#//BDD")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets a value indicating whether the current model element can be identified by an attribute value
        /// </summary>
        public override bool IsIdentified
        {
            get
            {
                return true;
            }
        }
        
        /// <summary>
        /// Gets fired before the Name property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> NameChanging;
        
        /// <summary>
        /// Gets fired when the Name property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> NameChanged;
        
        /// <summary>
        /// Gets fired before the Tree property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> TreeChanging;
        
        /// <summary>
        /// Gets fired when the Tree property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> TreeChanged;
        
        private static ITypedElement RetrieveNameAttribute()
        {
            return ((ITypedElement)(((ModelElement)(BDD.ClassInstance)).Resolve("name")));
        }
        
        /// <summary>
        /// Raises the NameChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnNameChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.NameChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the NameChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnNameChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.NameChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrievePortsReference()
        {
            return ((ITypedElement)(((ModelElement)(BDD.ClassInstance)).Resolve("ports")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Ports property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void PortsCollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Ports", e, _portsReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Ports property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void PortsCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Ports", e, _portsReference);
        }
        
        private static ITypedElement RetrieveTreeReference()
        {
            return ((ITypedElement)(((ModelElement)(BDD.ClassInstance)).Resolve("tree")));
        }
        
        /// <summary>
        /// Raises the TreeChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnTreeChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.TreeChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the TreeChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnTreeChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.TreeChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the Tree property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetTree(object sender, System.EventArgs eventArgs)
        {
            this.Tree = null;
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            int portsIndex = ModelHelper.IndexOfReference(this.Ports, element);
            if ((portsIndex != -1))
            {
                return ModelHelper.CreatePath("ports", portsIndex);
            }
            if ((element == this.Tree))
            {
                return ModelHelper.CreatePath("Tree");
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "PORTS"))
            {
                if ((index < this.Ports.Count))
                {
                    return this.Ports[index];
                }
                else
                {
                    return null;
                }
            }
            if ((reference == "TREE"))
            {
                return this.Tree;
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "NAME"))
            {
                return this.Name;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "PORTS"))
            {
                return this._ports;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "TREE"))
            {
                this.Tree = ((ITree)(value));
                return;
            }
            if ((feature == "NAME"))
            {
                this.Name = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "NAME"))
            {
                return new NameProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "TREE"))
            {
                return new TreeProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this._ports))
            {
                return "ports";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("https://www.transformation-tool-contest.eu/2019/bdd#//BDD")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Gets the identifier string for this model element
        /// </summary>
        /// <returns>The identifier string</returns>
        public override string ToIdentifierString()
        {
            if ((this.Name == null))
            {
                return null;
            }
            return this.Name.ToString();
        }
        
        /// <summary>
        /// The collection class to to represent the children of the BDD class
        /// </summary>
        public class BDDChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private BDD _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public BDDChildrenCollection(BDD parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Ports.Count);
                    if ((this._parent.Tree != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.Ports.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.TreeChanged += this.PropagateValueChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.Ports.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.TreeChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IPort portsCasted = item.As<IPort>();
                if ((portsCasted != null))
                {
                    this._parent.Ports.Add(portsCasted);
                }
                if ((this._parent.Tree == null))
                {
                    ITree treeCasted = item.As<ITree>();
                    if ((treeCasted != null))
                    {
                        this._parent.Tree = treeCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Ports.Clear();
                this._parent.Tree = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Ports.Contains(item))
                {
                    return true;
                }
                if ((item == this._parent.Tree))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> portsEnumerator = this._parent.Ports.GetEnumerator();
                try
                {
                    for (
                    ; portsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = portsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    portsEnumerator.Dispose();
                }
                if ((this._parent.Tree != null))
                {
                    array[arrayIndex] = this._parent.Tree;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IPort portItem = item.As<IPort>();
                if (((portItem != null) 
                            && this._parent.Ports.Remove(portItem)))
                {
                    return true;
                }
                if ((this._parent.Tree == item))
                {
                    this._parent.Tree = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Ports).Concat(this._parent.Tree).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the BDD class
        /// </summary>
        public class BDDReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private BDD _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public BDDReferencedElementsCollection(BDD parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Ports.Count);
                    if ((this._parent.Tree != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.Ports.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.TreeChanged += this.PropagateValueChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.Ports.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.TreeChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IPort portsCasted = item.As<IPort>();
                if ((portsCasted != null))
                {
                    this._parent.Ports.Add(portsCasted);
                }
                if ((this._parent.Tree == null))
                {
                    ITree treeCasted = item.As<ITree>();
                    if ((treeCasted != null))
                    {
                        this._parent.Tree = treeCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Ports.Clear();
                this._parent.Tree = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Ports.Contains(item))
                {
                    return true;
                }
                if ((item == this._parent.Tree))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> portsEnumerator = this._parent.Ports.GetEnumerator();
                try
                {
                    for (
                    ; portsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = portsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    portsEnumerator.Dispose();
                }
                if ((this._parent.Tree != null))
                {
                    array[arrayIndex] = this._parent.Tree;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IPort portItem = item.As<IPort>();
                if (((portItem != null) 
                            && this._parent.Ports.Remove(portItem)))
                {
                    return true;
                }
                if ((this._parent.Tree == item))
                {
                    this._parent.Tree = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Ports).Concat(this._parent.Tree).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the name property
        /// </summary>
        private sealed class NameProxy : ModelPropertyChange<IBDD, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public NameProxy(IBDD modelElement) : 
                    base(modelElement, "name")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Name;
                }
                set
                {
                    this.ModelElement.Name = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the tree property
        /// </summary>
        private sealed class TreeProxy : ModelPropertyChange<IBDD, ITree>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public TreeProxy(IBDD modelElement) : 
                    base(modelElement, "tree")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override ITree Value
            {
                get
                {
                    return this.ModelElement.Tree;
                }
                set
                {
                    this.ModelElement.Tree = value;
                }
            }
        }
    }
}

